# Model parameters.
model:
  model: "hatformer_baseline_and_BHE_FME_AFA"
  2d_loss: 'bce'
  3d_loss: 'mse'
  num_classes: 3
  loss_weights: [1,1]
  2d_loss_weights: [0.05, 0.95, 0.95]
  weight2d: [1.0,1.0,1.0,1.0]
  weight3d: [1.0,1.0,1.0,1.0]
  weightbg: 1.0
  weightunc: 0.1
  pretrain_path: 'results/CD_bfcdnet_levir/epoch=299-step=66900.ckpt'

# Optimization parameters.
optim:
  num_epochs: 600
  lr: 0.0001
  optim_type: "adamw"
  momentum: 0.9
  nesterov: False
  beta: [0.9, 0.999]
  end_lr: 0.000005
  weight_decay: 0.001
  lr_schedule_type: "step_lr"
  step: 300
  gamma: 0.75
  last_epoch: 10

# Data parameters:
data:
  max_value: 83.266
  min_value: -27.291
  max_value_dsm: 99
  min_value_dsm: -10
  augmentations: True
  mean: [0.5896145210542503, 0.6210658017517566, 0.591661801751776]
  std: [0.1898555514094201, 0.19114699478664082, 0.21242997453209553]
  batch_size: 4
  train:
    path: ['../data/SMARS/SVenice_dsm2img/train','../data/SMARS/SVenice_img2dsm/train',
           ]
  val:
    path: ['../data/SMARS/SVenice_dsm2img/val','../data/SMARS/SVenice_img2dsm/val',
           ]
  test:
    path: ['../data/SMARS/SVenice_dsm2img/test','../data/SMARS/SVenice_img2dsm/test'
           ]


  sets: ['img/','dsm/','mask2d/','mask3d/']
